### ISSUE TITLE
Support muti Boards

### ISSUE THREAD

**Issue by zhiyelee** [zhiyelee/trello-issue#3]
Support muti Boards, should rewrite the format of  `conf/config.sample.yml`

``` yml
{
  BoardId1:
      appKey: ***
      oauthToken: ***
      numbersLength: 4
      # *** snip **
  Board2:
      appKey: ***
      oauthToken: ***
      numbersLength: 4
      # *** snip **      
}
```
